---

# tasks file for ansible-role-container-registry

- name: perform docker login
  become: true
  docker_login:
    username: "{{ lookup('dict', item.value).key }}"
    password: "{{ lookup('dict', item.value).value }}"
    registry: "{{ item.key }}"
  loop: "{{ query('dict', container_registry_logins | default({})) }}"
  when: container_registry_logins | length > 0
